### ISSUE TITLE
 Raspberry Pi connection to ST tiller pilot

### ISSUE THREAD

**Issue by spagnuolocarmine** [marcobergman/remote_pilot#1]
First of all, thank you for your interesting work.

I am not an expert in electronics stuff, but I would like to the same project.

Could you give some information about the connection between the Pi and the ST. I understand that the ST connection has 3 cable Yellow (data seatalk), Red (12v), Black (GND).. is it possible to connect the Pi to the ST directly on this cable?

I am sorry for these questions, that maybe can be seen as not good ones.

Thank you in advance

**Comment by marcobergman** [comment]
Hi Carmine, thank you for your question, and it's good you ask. I
understand your want to know whether you can connect the pi output directly
to the yellow seatalk connection. This is not possible; you are likely to
damage your pi output. The seatalk input is normally 'pulled up' to +12V, a
pi output is limited to dealing with 3.3 volts only.

Also, the red cable of the seatalk cabling normally carries +12 volts,
whereas the PI would require no more than 5V.

So you would need a separate 5 volt power supply to feed your pi, and you
would need at least the 'level shifter' circuit as given by the ascii art
in the code. This is not difficult to make; any first year electronics
student can cook it up.

You ought to know that I don't follow the seatalk protocol strictly, which
is quite difficult to do, as it would require checking for collisions on
the seatalk line while you are sending yourself. Not doing so can result in
collisions, meaning, lost data.  For my purposes this is not a real
problem; I have this in use on my boat.

Kind regards,

/Marco Bergman

**Comment by spagnuolocarmine** [comment]
Really thank you for your quick replay.

best
